keys:
  - &astora age1u9xr3tmwskfsrxg6gus3hmh9eakjh2h22jklfmcu33kassaraues435vvc
  - &catarina age1wyz7cfldqe9hh8qyw2qm42hkq9s7qdwqnrnv0u3s6vstv9649v0sh0z4em
creation_rules:
  - path_regex: catarina.(yaml|env|txt)$
    key_groups:
      - age:
          - *astora
          - *catarina
